name = "clima-tracker-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[[kv_namespaces]]
binding = "ALERT_CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[[triggers]]
crons = ["*/15 * * * *"]
